### ISSUE TITLE
Ruby version: 2.1.0 is not supported.

### ISSUE THREAD

**Issue by dfyx** [shuky19/sublime_debugger#23]
As the title says. I don't see why the plugin shouldn't at least try to let me debug ruby 2.1.0. There aren't that many changes and byebug works just fine.

**Comment by buffonomics** [comment]
OKay I'm getting 
--
Stopping...
Ruby version: 2.2.0 is not supported.
--

Not sure how to use rube discoverer file exactly.
This is my ruby version:
--
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
--

So I change the ruby_version_discoverer.rb file to:
---
puts 2.2.0
---

Now I get 
--
Stopping...
Ruby version:  is not supported.
---

It doesn't even acknowledge the version i entered in the report...

**Comment by jhigman** [comment]
I had to add my Ruby version (2.1.1) to the list of supported versions in the "Ruby Debugger.sublime-settings" file, so it looked like this:

  "supported_ruby_versions": ["2.1.1", "2.1.0", "2.0.0", "1.9.3"]

After that the debugger started ok.

**Comment by dregules** [comment]
@jhigman - Also did that for 2.2.1 and I don't seem to get it to work. 
For all I get is this below, every time I Debug:

```
Connecting... 
Connected
/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `write': closed stream (IOError)
Last exception: #<IOError: closed stream>
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `puts'
Backtrace: 
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `puts'
["/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `write'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `puts'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/interface.rb:67:in `puts'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/commands/list.rb:115:in `display_lines'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/commands/list.rb:26:in `execute'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `block in always_run'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `each'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `always_run'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:90:in `process_commands'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:52:in `at_return'", "/Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/context.rb:94:in `at_return'", "/Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:14:in `block in <top (required)>'", "/Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `call'", "/Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `<top (required)>'", "/Users/diegoregules/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "/Users/diegoregules/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'"]
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/commands/list.rb:115:in `display_lines'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/commands/list.rb:26:in `execute'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `block in always_run'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `each'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:79:in `always_run'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:90:in `process_commands'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:52:in `at_return'
  from /Users/diegoregules/.rvm/gems/ruby-2.2.1/gems/byebug-5.0.0/lib/byebug/context.rb:94:in `at_return'
  from /Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:14:in `block in <top (required)>'
  from /Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `call'
  from /Users/diegoregules/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `<top (required)>'
  from /Users/diegoregules/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/diegoregules/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Debugger stopped
                              
```
Does it happen to you too? @shuky19 any insight on this greatly appreciated. Thank you in advance!
