### ISSUE TITLE
Must call on main thread

### ISSUE THREAD

**Issue by bachue** [shuky19/sublime_debugger#26]
Environment: Sublime 2, Ruby 2.1.2, Byebug 3.1.2 installed.

I just try to debug ruby code like that:

``` ruby
class C
  def f a
    a + 1
  end
end

a = 1

C.new.f a
```

It doesn't work, I tried all commands but failed.
This is the log from SublimeLog:

```
=> => => Console logging activated (/Users/bachue/.subl.log). Timestamp: 10 Jun 2014, 00:22:01.
Exception in thread Thread-1722:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./debug_command.py", line 88, in <lambda>
    SublimeHelper.set_timeout_async(lambda file_path=file_path,bundle=use_bundler, args=arguments: self.start_command_async(file_path, bundle, *args), 0)
  File "./debug_command.py", line 101, in start_command_async
    self.debugger.run_command(DebuggerModel.COMMAND_START, PathHelper.get_pwd(file_path), file_path, *args)
  File "./debugger/ruby_imp/ruby_debugger.py", line 47, in run_command
    RubyDebugger.COMMANDS[command_type].execute(self.connector, *args)
  File "./debugger/ruby_imp/ruby_custom_debug_command.py", line 10, in execute
    self.lambda_command(debugger_constroller, *args)
  File "./debugger/ruby_imp/ruby_debugger.py", line 25, in <lambda>
    DebuggerModel.COMMAND_START:RubyCustomDebugCommand(lambda debugger_constroller, *args: debugger_constroller.start(*args)),
  File "./debugger/ruby_imp/ruby_debugger_connector.py", line 46, in start
    self.start_process(current_directory, file_name, args)
  File "./debugger/ruby_imp/ruby_debugger_connector.py", line 97, in start_process
    self.process = subprocess.Popen(" ".join(process_params), stdin = subprocess.PIPE, stderr = subprocess.PIPE, stdout=subprocess.PIPE, bufsize=1, shell=True, cwd=sublime.active_window().folders()[0])
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

**Comment by JSmith2412** [comment]
...Having same problem, environment is as follows:
OS : Windows 7 64 bit
Sublime : 2.0.2
Ruby : 2.5.1
Rails : 4.1.8
ByeBug : 5.0.0
Python : 2.7.10

Output : 
>Exception in thread Thread-41:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\debug_command.py", line 92, in <lambda>
  File ".\debug_command.py", line 98, in start_command_async
  File ".\debugger\ruby_imp\ruby_debugger.py", line 47, in run_command
  File ".\debugger\ruby_imp\ruby_custom_debug_command.py", line 10, in execute
  File ".\debugger\ruby_imp\ruby_debugger.py", line 26, in <lambda>
  File ".\debugger\ruby_imp\ruby_debugger_connector.py", line 323, in stop
  File ".\debugger\interfaces\debugger_connector.py", line 17, in log_message
  File ".\debugger\interfaces\debugger.py", line 19, in signal_text_result
  File ".\debug_command.py", line 149, in add_text_result
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

**Comment by JSmith2412** [comment]
...Resolved by upgrading to Sublime Text 3....
