### ISSUE TITLE
byebug closed stream (IOError)

### ISSUE THREAD

**Issue by ConfusedVorlon** [shuky19/sublime_debugger#46]
I'm using byebug 4.05 (but get the same error with byebug5) with ruby 2.0.0p594 and sublime text 3

I have checked that my rails app runs correctly using the same rvm ruby as ruby debugger, and byebug triggers and runs (when using rake test on the command line)

as soon as I run an app (shift F6) I get the error below.

any suggestions?

thanks in advance.

```

Started process command: bash -c "'/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/ruby_executor.sh' 'rvm' True  '-C/Users/rob/Documents/Development/Rails/SetupHelp4' '-r/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb' '-rbundler/setup'   'bin/rails' s"
Connecting... 

----------------------------------------
------------Ruby Executor---------------
----------------------------------------
Method: RVM
Using ruby version: ruby 2.0.0p594 (2014-10-27 revision 48167) [x86_64-darwin14.1.0]
Located at: /Users/rob/.rvm/rubies/ruby-2.0.0-p594/bin/ruby
Ruby Arguments = -C/Users/rob/Documents/Development/Rails/SetupHelp4 -r/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb -rbundler/setup bin/rails s

Connected
/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `write': closed stream (IOError)
Last exception: #<IOError: closed stream>
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `puts'
Backtrace: 
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `puts'
["/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `write'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `puts'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/interface.rb:65:in `puts'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/commands/list.rb:116:in `display_lines'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/commands/list.rb:21:in `execute'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:79:in `block in always_run'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:78:in `each'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:78:in `always_run'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:87:in `process_commands'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:51:in `at_return'", "/Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/context.rb:94:in `at_return'", "/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:14:in `block in <top (required)>'", "/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `call'", "/Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `<top (required)>'", "/Users/rob/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "/Users/rob/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'"]
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/commands/list.rb:116:in `display_lines'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/commands/list.rb:21:in `execute'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:79:in `block in always_run'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:78:in `each'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:78:in `always_run'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:87:in `process_commands'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/processors/command_processor.rb:51:in `at_return'
	from /Users/rob/.rvm/gems/ruby-2.0.0-p594/gems/byebug-4.0.5/lib/byebug/context.rb:94:in `at_return'
	from /Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:14:in `block in <top (required)>'
	from /Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `call'
	from /Users/rob/Library/Application Support/Sublime Text 3/Packages/Ruby Debugger/sublime_debug_require.rb:37:in `<top (required)>'
	from /Users/rob/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rob/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Debugger stopped
															

```

**Comment by threadhead** [comment]
+1

**Comment by johntrandall** [comment]
+1 
using rbenv, Ruby 2.1.0, and byebug 5.0.0

**Comment by rhapsodyv** [comment]
I think it's a byebug error: https://github.com/deivid-rodriguez/byebug/commit/90cdfcc9cee8ba6362bad2185390cbe4fa85845d

Changing handler.interface to just interface solved all the problems for me.
